# Generated by Django 4.2.5 on 2023-10-23 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("ethanapp", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="people",
            field=models.ManyToManyField(blank=True, to="ethanapp.person"),
        ),
        migrations.CreateModel(
            name="MoviePerson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "movie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="ethanapp.movie"
                    ),
                ),
                (
                    "person",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="ethanapp.person",
                    ),
                ),
            ],
            options={
                "unique_together": {("movie", "person")},
            },
        ),
    ]
