# Generated by Django 4.2.5 on 2023-10-23 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ethanapp", "0002_alter_movie_people_movieperson"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="movie",
            name="people",
        ),
        migrations.AddField(
            model_name="movieperson",
            name="role",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
